/* The following code was generated by JFlex 1.7.0 */

/*Primera seccion, librerias */
package gramatica;
import java_cup.runtime.*;
import static gramatica.ParserLecturaSym.*;
import clasesDAO.Token;
import clasesDAO.TokenError;
import java.util.ArrayList;

/*Segunda seccion, config*/

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>./jflexLectura.jflex</tt>
 */
public class LexerLectura implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\10\57\3\1\1\57\2\1\22\57\1\1\1\55\1\51\5\55\1\2"+
    "\1\4\2\55\1\5\1\55\1\50\1\55\1\46\11\47\1\55\1\3"+
    "\5\55\1\10\1\44\1\25\1\23\1\22\1\24\1\42\1\40\1\12"+
    "\2\60\1\32\1\60\1\33\1\13\2\60\1\11\1\7\1\36\1\6"+
    "\5\60\2\55\1\56\3\55\1\16\1\45\1\30\1\26\1\31\1\27"+
    "\1\43\1\41\1\20\2\60\1\34\1\60\1\35\1\21\2\60\1\17"+
    "\1\14\1\37\1\15\5\60\4\55\143\0\1\52\160\0\1\54\u1f58\0"+
    "\1\53\udf50\0\1\54\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\22\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\21\1\2\3\2\1\1\4\1\5"+
    "\1\6\1\7\1\10\73\0\1\3\35\0\1\3\3\0"+
    "\1\11\11\0\1\12\14\0\1\3\4\0\1\11\10\0"+
    "\1\12\11\0\1\3\1\13\1\14\16\0\1\15\1\0"+
    "\1\13\1\14\2\0\1\16\10\0\1\15\11\0\1\16"+
    "\1\17\7\0\1\20\1\21\2\0\1\17\1\20\1\21";

  private static int [] zzUnpackAction() {
    int [] result = new int[227];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\61\0\61\0\142\0\223\0\304\0\365\0\u0126"+
    "\0\u0157\0\u0188\0\u01b9\0\u01ea\0\u021b\0\u024c\0\u027d\0\u02ae"+
    "\0\u02df\0\u0310\0\u0341\0\u0372\0\u03a3\0\u03d4\0\u0405\0\u0436"+
    "\0\61\0\61\0\61\0\61\0\61\0\u01b9\0\u0467\0\u0498"+
    "\0\u04c9\0\u04fa\0\u052b\0\u055c\0\u058d\0\u05be\0\u05ef\0\u0620"+
    "\0\u0651\0\u0682\0\u06b3\0\u06e4\0\u0715\0\u0746\0\u0777\0\u07a8"+
    "\0\u07d9\0\u080a\0\u083b\0\u086c\0\u089d\0\u08ce\0\u08ff\0\u0930"+
    "\0\u0961\0\u0992\0\u09c3\0\u09f4\0\u0a25\0\u0a56\0\u0a87\0\u0ab8"+
    "\0\u0ae9\0\u0b1a\0\u0b4b\0\u0b7c\0\u0bad\0\u0bde\0\u0c0f\0\u0c40"+
    "\0\u0c71\0\u0ca2\0\u0cd3\0\u0d04\0\u0d35\0\u0d66\0\u0d97\0\u0dc8"+
    "\0\u0df9\0\u0e2a\0\u0e5b\0\u0e8c\0\u0ebd\0\u0eee\0\u0f1f\0\u0f50"+
    "\0\u0f81\0\u0fb2\0\u0405\0\u0fe3\0\u1014\0\u1045\0\u1076\0\u10a7"+
    "\0\u10d8\0\u1109\0\u113a\0\u116b\0\u119c\0\u11cd\0\u11fe\0\u122f"+
    "\0\u1260\0\u1291\0\u12c2\0\u12f3\0\u1324\0\u1355\0\u1386\0\u13b7"+
    "\0\u13e8\0\u1419\0\u144a\0\u147b\0\u14ac\0\u14dd\0\u150e\0\u153f"+
    "\0\u1570\0\u15a1\0\u01b9\0\u15d2\0\u1603\0\u1634\0\u1665\0\u1696"+
    "\0\u16c7\0\u16f8\0\u1729\0\u175a\0\u01b9\0\u178b\0\u17bc\0\u17ed"+
    "\0\u181e\0\u184f\0\u1880\0\u18b1\0\u18e2\0\u1913\0\u1944\0\u1975"+
    "\0\u19a6\0\u19d7\0\u1a08\0\u1a39\0\u1a6a\0\u1a9b\0\61\0\u1acc"+
    "\0\u1afd\0\u1b2e\0\u1b5f\0\u1b90\0\u1bc1\0\u1bf2\0\u1c23\0\61"+
    "\0\u1c54\0\u1c85\0\u1cb6\0\u1ce7\0\u1d18\0\u1d49\0\u1d7a\0\u1dab"+
    "\0\u1ddc\0\61\0\u01b9\0\u01b9\0\u1e0d\0\u1e3e\0\u1e6f\0\u1ea0"+
    "\0\u1ed1\0\u1f02\0\u1f33\0\u1f64\0\u1f95\0\u1fc6\0\u1ff7\0\u2028"+
    "\0\u2059\0\u208a\0\u01b9\0\u20bb\0\61\0\61\0\u20ec\0\u211d"+
    "\0\u01b9\0\u214e\0\u217f\0\u21b0\0\u21e1\0\u2212\0\u2243\0\u2274"+
    "\0\u22a5\0\61\0\u22d6\0\u2307\0\u2338\0\u2369\0\u239a\0\u23cb"+
    "\0\u23fc\0\u242d\0\u245e\0\61\0\u01b9\0\u248f\0\u24c0\0\u24f1"+
    "\0\u2522\0\u2553\0\u2584\0\u25b5\0\u01b9\0\u01b9\0\u25e6\0\u2617"+
    "\0\61\0\61\0\61";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[227];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\3\13\1\14\1\15\1\16\3\13\1\17\2\13"+
    "\1\20\2\13\1\21\1\22\6\13\1\23\1\24\4\13"+
    "\1\25\1\26\1\2\1\27\1\30\5\2\1\13\64\0"+
    "\1\31\60\0\1\32\60\0\1\33\60\0\1\34\60\0"+
    "\1\35\2\0\1\36\1\37\4\36\1\40\33\36\10\0"+
    "\1\36\3\0\1\35\2\0\2\36\1\41\5\36\1\42"+
    "\31\36\10\0\1\36\3\0\1\35\2\0\1\36\1\43"+
    "\4\36\1\44\33\36\10\0\1\36\3\0\1\35\2\0"+
    "\42\36\10\0\1\36\3\0\1\35\2\0\10\36\1\45"+
    "\31\36\10\0\1\36\3\0\1\35\2\0\6\36\1\46"+
    "\33\36\10\0\1\36\3\0\1\35\2\0\6\36\1\47"+
    "\33\36\10\0\1\36\3\0\1\35\2\0\1\36\1\50"+
    "\4\36\1\51\6\36\1\52\2\36\1\53\21\36\10\0"+
    "\1\36\3\0\1\35\2\0\1\54\1\36\1\55\2\36"+
    "\1\56\1\36\1\57\1\60\2\36\1\61\26\36\10\0"+
    "\1\36\3\0\1\35\2\0\7\36\1\62\1\63\2\36"+
    "\1\64\26\36\10\0\1\36\3\0\1\35\2\0\6\36"+
    "\1\65\11\36\1\66\21\36\10\0\1\36\3\0\1\35"+
    "\2\0\5\36\1\67\5\36\1\70\26\36\10\0\1\36"+
    "\3\0\1\35\2\0\13\36\1\71\26\36\10\0\1\36"+
    "\3\0\1\35\2\0\42\36\1\72\7\0\1\36\3\0"+
    "\1\35\2\0\40\36\2\26\1\72\7\0\1\36\1\0"+
    "\50\73\4\0\1\73\1\74\2\73\53\0\1\75\10\0"+
    "\1\35\2\0\1\76\41\36\10\0\1\36\3\0\1\35"+
    "\2\0\7\36\1\77\32\36\10\0\1\36\3\0\1\35"+
    "\2\0\24\36\1\100\15\36\10\0\1\36\3\0\1\35"+
    "\2\0\26\36\1\101\13\36\10\0\1\36\3\0\1\35"+
    "\2\0\4\36\1\102\35\36\10\0\1\36\3\0\1\35"+
    "\2\0\12\36\1\103\27\36\10\0\1\36\3\0\1\35"+
    "\2\0\26\36\1\104\13\36\10\0\1\36\3\0\1\35"+
    "\2\0\7\36\1\105\32\36\10\0\1\36\3\0\1\35"+
    "\2\0\12\36\1\106\27\36\10\0\1\36\3\0\1\35"+
    "\2\0\30\36\1\107\11\36\10\0\1\36\3\0\1\35"+
    "\2\0\31\36\1\110\10\36\10\0\1\36\3\0\1\35"+
    "\2\0\4\36\1\111\35\36\10\0\1\36\3\0\1\35"+
    "\2\0\12\36\1\112\27\36\10\0\1\36\3\0\1\35"+
    "\2\0\3\36\1\113\36\36\10\0\1\36\3\0\1\35"+
    "\2\0\30\36\1\114\11\36\10\0\1\36\3\0\1\35"+
    "\2\0\24\36\1\115\15\36\10\0\1\36\3\0\1\35"+
    "\2\0\11\36\1\116\30\36\10\0\1\36\3\0\1\35"+
    "\2\0\31\36\1\117\10\36\10\0\1\36\3\0\1\35"+
    "\2\0\26\36\1\120\13\36\10\0\1\36\3\0\1\35"+
    "\2\0\11\36\1\121\30\36\10\0\1\36\3\0\1\35"+
    "\2\0\31\36\1\122\10\36\10\0\1\36\3\0\1\35"+
    "\2\0\26\36\1\123\13\36\10\0\1\36\3\0\1\35"+
    "\2\0\31\36\1\124\10\36\10\0\1\36\3\0\1\35"+
    "\2\0\12\36\1\125\27\36\10\0\1\36\3\0\1\35"+
    "\2\0\3\36\1\126\36\36\10\0\1\36\3\0\1\35"+
    "\2\0\11\36\1\127\30\36\10\0\1\36\3\0\1\35"+
    "\2\0\11\36\1\130\30\36\10\0\1\36\46\0\2\131"+
    "\12\0\50\73\1\35\1\132\2\0\1\73\1\74\2\73"+
    "\1\0\1\74\4\0\40\73\11\0\1\74\1\73\54\0"+
    "\1\133\7\0\1\35\2\0\2\36\1\134\37\36\10\0"+
    "\1\36\3\0\1\35\2\0\10\36\1\135\31\36\10\0"+
    "\1\36\3\0\1\35\2\0\5\36\1\136\34\36\10\0"+
    "\1\36\3\0\1\35\2\0\13\36\1\137\26\36\10\0"+
    "\1\36\3\0\1\35\2\0\34\36\1\140\5\36\10\0"+
    "\1\36\3\0\1\35\2\0\35\36\1\141\4\36\10\0"+
    "\1\36\3\0\1\35\2\0\13\36\1\142\26\36\10\0"+
    "\1\36\3\0\1\35\2\0\10\36\1\143\31\36\10\0"+
    "\1\36\3\0\1\35\2\0\35\36\1\144\4\36\10\0"+
    "\1\36\3\0\1\35\2\0\1\145\41\36\10\0\1\36"+
    "\3\0\1\35\2\0\7\36\1\146\32\36\10\0\1\36"+
    "\3\0\1\35\2\0\16\36\1\147\23\36\10\0\1\36"+
    "\3\0\1\35\2\0\21\36\1\150\20\36\10\0\1\36"+
    "\3\0\1\35\2\0\1\36\1\151\40\36\10\0\1\36"+
    "\3\0\1\35\2\0\14\36\1\152\25\36\10\0\1\36"+
    "\3\0\1\35\2\0\2\36\1\153\37\36\10\0\1\36"+
    "\3\0\1\35\2\0\6\36\1\154\33\36\10\0\1\36"+
    "\3\0\1\35\2\0\23\36\1\155\16\36\10\0\1\36"+
    "\3\0\1\35\2\0\10\36\1\156\31\36\10\0\1\36"+
    "\3\0\1\35\2\0\6\36\1\157\33\36\10\0\1\36"+
    "\3\0\1\35\2\0\23\36\1\160\16\36\10\0\1\36"+
    "\3\0\1\35\2\0\10\36\1\161\31\36\10\0\1\36"+
    "\3\0\1\35\2\0\7\36\1\162\32\36\10\0\1\36"+
    "\3\0\1\35\2\0\21\36\1\163\20\36\10\0\1\36"+
    "\3\0\1\35\2\0\2\36\1\164\37\36\10\0\1\36"+
    "\3\0\1\35\2\0\10\36\1\165\31\36\10\0\1\36"+
    "\3\0\1\35\2\0\10\36\1\166\31\36\10\0\1\36"+
    "\46\0\2\167\64\0\1\170\10\0\1\35\2\0\3\36"+
    "\1\171\36\36\10\0\1\36\3\0\1\35\2\0\11\36"+
    "\1\172\30\36\10\0\1\36\3\0\1\35\2\0\25\36"+
    "\1\173\14\36\10\0\1\36\3\0\1\35\2\0\27\36"+
    "\1\173\12\36\10\0\1\36\3\0\1\35\2\0\25\36"+
    "\1\174\14\36\10\0\1\36\3\0\1\35\2\0\27\36"+
    "\1\175\12\36\10\0\1\36\3\0\1\35\2\0\27\36"+
    "\1\176\12\36\10\0\1\36\3\0\1\35\2\0\11\36"+
    "\1\177\30\36\10\0\1\36\3\0\1\35\2\0\27\36"+
    "\1\200\12\36\10\0\1\36\3\0\1\35\2\0\15\36"+
    "\1\201\24\36\10\0\1\36\3\0\1\35\2\0\20\36"+
    "\1\202\21\36\10\0\1\36\3\0\1\35\2\0\4\36"+
    "\1\203\35\36\10\0\1\36\3\0\1\35\2\0\12\36"+
    "\1\204\27\36\10\0\1\36\3\0\1\35\2\0\5\36"+
    "\1\205\34\36\10\0\1\36\3\0\1\35\2\0\15\36"+
    "\1\206\24\36\10\0\1\36\3\0\1\35\2\0\36\36"+
    "\1\207\3\36\10\0\1\36\3\0\1\35\2\0\13\36"+
    "\1\210\26\36\10\0\1\36\3\0\1\35\2\0\20\36"+
    "\1\211\21\36\10\0\1\36\3\0\1\35\2\0\37\36"+
    "\1\212\2\36\10\0\1\36\3\0\1\35\2\0\13\36"+
    "\1\205\26\36\10\0\1\36\3\0\1\35\2\0\20\36"+
    "\1\213\21\36\10\0\1\36\3\0\1\35\2\0\37\36"+
    "\1\214\2\36\10\0\1\36\3\0\1\35\2\0\20\36"+
    "\1\215\21\36\10\0\1\36\3\0\1\35\2\0\12\36"+
    "\1\216\27\36\10\0\1\36\3\0\1\35\2\0\3\36"+
    "\1\217\36\36\10\0\1\36\3\0\1\35\2\0\11\36"+
    "\1\220\30\36\10\0\1\36\3\0\1\35\2\0\11\36"+
    "\1\221\30\36\10\0\1\36\46\0\2\222\65\0\1\35"+
    "\7\0\1\35\2\0\4\36\1\223\35\36\10\0\1\36"+
    "\3\0\1\35\2\0\12\36\1\224\27\36\10\0\1\36"+
    "\3\0\1\35\2\0\2\36\1\225\37\36\10\0\1\36"+
    "\3\0\1\35\2\0\10\36\1\226\31\36\10\0\1\36"+
    "\3\0\1\227\2\0\42\36\10\0\1\36\3\0\1\35"+
    "\2\0\12\36\1\230\27\36\10\0\1\36\3\0\1\35"+
    "\2\0\10\36\1\231\31\36\10\0\1\36\3\0\1\35"+
    "\2\0\4\36\1\232\35\36\10\0\1\36\3\0\1\35"+
    "\2\0\12\36\1\233\27\36\10\0\1\36\3\0\1\35"+
    "\2\0\17\36\1\234\22\36\10\0\1\36\3\0\1\35"+
    "\2\0\22\36\1\235\17\36\10\0\1\36\3\0\1\35"+
    "\2\0\3\36\1\236\36\36\10\0\1\36\3\0\1\35"+
    "\2\0\5\36\1\237\34\36\10\0\1\36\3\0\1\240"+
    "\2\0\42\36\10\0\1\36\3\0\1\35\2\0\11\36"+
    "\1\241\30\36\10\0\1\36\3\0\1\35\2\0\13\36"+
    "\1\242\26\36\10\0\1\36\3\0\1\35\2\0\11\36"+
    "\1\243\30\36\10\0\1\36\3\0\1\35\2\0\13\36"+
    "\1\244\26\36\10\0\1\36\3\0\1\35\2\0\12\36"+
    "\1\245\27\36\10\0\1\36\3\0\1\35\2\0\22\36"+
    "\1\246\17\36\10\0\1\36\3\0\1\35\2\0\4\36"+
    "\1\247\35\36\10\0\1\36\3\0\1\35\2\0\12\36"+
    "\1\250\27\36\10\0\1\36\3\0\1\35\2\0\12\36"+
    "\1\251\27\36\10\0\1\36\47\0\1\252\14\0\1\35"+
    "\2\0\5\36\1\253\34\36\10\0\1\36\3\0\1\35"+
    "\2\0\13\36\1\253\26\36\10\0\1\36\3\0\1\35"+
    "\2\0\3\36\1\254\36\36\10\0\1\36\3\0\1\35"+
    "\2\0\11\36\1\254\30\36\10\0\1\36\3\0\1\35"+
    "\2\0\13\36\1\255\26\36\10\0\1\36\3\0\1\35"+
    "\2\0\11\36\1\256\30\36\10\0\1\36\3\0\1\35"+
    "\2\0\2\36\1\257\37\36\10\0\1\36\3\0\1\35"+
    "\2\0\10\36\1\260\31\36\10\0\1\36\3\0\1\35"+
    "\2\0\4\36\1\261\35\36\10\0\1\36\3\0\1\35"+
    "\2\0\12\36\1\262\27\36\10\0\1\36\3\0\1\35"+
    "\2\0\2\36\1\263\37\36\10\0\1\36\3\0\1\35"+
    "\2\0\3\36\1\264\36\36\10\0\1\36\3\0\1\35"+
    "\2\0\10\36\1\265\31\36\10\0\1\36\3\0\1\35"+
    "\2\0\11\36\1\266\30\36\10\0\1\36\3\0\1\35"+
    "\2\0\10\36\1\267\31\36\10\0\1\36\3\0\1\35"+
    "\2\0\11\36\1\270\30\36\10\0\1\36\3\0\1\35"+
    "\2\0\10\36\1\271\31\36\10\0\1\36\3\0\1\35"+
    "\2\0\12\36\1\272\27\36\10\0\1\36\3\0\1\35"+
    "\2\0\5\36\1\273\34\36\10\0\1\36\3\0\1\35"+
    "\2\0\13\36\1\274\26\36\10\0\1\36\3\0\1\35"+
    "\2\0\13\36\1\273\26\36\10\0\1\36\3\0\1\275"+
    "\2\0\42\36\10\0\1\36\3\0\1\276\2\0\42\36"+
    "\10\0\1\36\3\0\1\35\2\0\25\36\1\277\14\36"+
    "\10\0\1\36\3\0\1\35\2\0\27\36\1\300\12\36"+
    "\10\0\1\36\3\0\1\35\2\0\5\36\1\301\34\36"+
    "\10\0\1\36\3\0\1\35\2\0\13\36\1\301\26\36"+
    "\10\0\1\36\3\0\1\35\2\0\30\36\1\302\11\36"+
    "\10\0\1\36\3\0\1\35\2\0\2\36\1\303\37\36"+
    "\10\0\1\36\3\0\1\35\2\0\31\36\1\304\10\36"+
    "\10\0\1\36\3\0\1\35\2\0\10\36\1\305\31\36"+
    "\10\0\1\36\3\0\1\35\2\0\31\36\1\306\10\36"+
    "\10\0\1\36\3\0\1\35\2\0\10\36\1\307\31\36"+
    "\10\0\1\36\3\0\1\35\2\0\27\36\1\310\12\36"+
    "\10\0\1\36\3\0\1\35\2\0\13\36\1\311\26\36"+
    "\10\0\1\36\3\0\1\312\2\0\42\36\10\0\1\36"+
    "\3\0\1\35\2\0\30\36\1\313\11\36\10\0\1\36"+
    "\3\0\1\35\2\0\31\36\1\314\10\36\10\0\1\36"+
    "\3\0\1\35\2\0\4\36\1\315\35\36\10\0\1\36"+
    "\3\0\1\35\2\0\15\36\1\316\24\36\10\0\1\36"+
    "\3\0\1\35\2\0\12\36\1\317\27\36\10\0\1\36"+
    "\3\0\1\35\2\0\20\36\1\320\21\36\10\0\1\36"+
    "\3\0\1\35\2\0\12\36\1\321\27\36\10\0\1\36"+
    "\3\0\1\35\2\0\20\36\1\322\21\36\10\0\1\36"+
    "\3\0\1\35\2\0\31\36\1\323\10\36\10\0\1\36"+
    "\3\0\1\324\2\0\42\36\10\0\1\36\3\0\1\35"+
    "\2\0\14\36\1\325\25\36\10\0\1\36\3\0\1\35"+
    "\2\0\23\36\1\325\16\36\10\0\1\36\3\0\1\35"+
    "\2\0\17\36\1\326\22\36\10\0\1\36\3\0\1\35"+
    "\2\0\5\36\1\327\34\36\10\0\1\36\3\0\1\35"+
    "\2\0\22\36\1\330\17\36\10\0\1\36\3\0\1\35"+
    "\2\0\13\36\1\331\26\36\10\0\1\36\3\0\1\35"+
    "\2\0\22\36\1\332\17\36\10\0\1\36\3\0\1\35"+
    "\2\0\13\36\1\333\26\36\10\0\1\36\3\0\1\35"+
    "\2\0\23\36\1\334\16\36\10\0\1\36\3\0\1\35"+
    "\2\0\5\36\1\335\34\36\10\0\1\36\3\0\1\35"+
    "\2\0\3\36\1\336\36\36\10\0\1\36\3\0\1\35"+
    "\2\0\13\36\1\337\26\36\10\0\1\36\3\0\1\35"+
    "\2\0\11\36\1\340\30\36\10\0\1\36\3\0\1\35"+
    "\2\0\13\36\1\335\26\36\10\0\1\36\3\0\1\35"+
    "\2\0\11\36\1\336\30\36\10\0\1\36\3\0\1\341"+
    "\2\0\42\36\10\0\1\36\3\0\1\342\2\0\42\36"+
    "\10\0\1\36\3\0\1\343\2\0\42\36\10\0\1\36";

  private static int [] zzUnpackTrans() {
    int [] result = new int[9800];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\25\1\5\11\73\0\1\1\35\0\1\1"+
    "\3\0\1\1\11\0\1\1\14\0\1\1\4\0\1\11"+
    "\10\0\1\11\11\0\1\11\2\1\16\0\1\1\1\0"+
    "\2\11\2\0\1\1\10\0\1\11\11\0\1\11\1\1"+
    "\7\0\2\1\2\0\3\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[227];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    //Creamos un listado de llos errores lexicos
    ArrayList<TokenError> listadoErroresLexicos = new ArrayList();

    //Funciones
    //retorna un simbolo despues de crear un nuevo token y agregarlo al listado
    private Symbol retornarSimbolo(int tipo, String tipoToken, String lexema, int fila, int columna){
        //creamos un  token auxiliar
        Token tokenAux = new Token(tipoToken, lexema, fila, columna);
        System.out.println("Fila: "+fila+" Columa: "+columna+" Token: "+tipoToken+ " Lexema: "+lexema);
        //retornamos el token aux como simbolo
        return new Symbol(tipo, tokenAux);
    }
    
    //Agregamos un token al array list de errores lexicos
    private void addErrorLexico(String tipoToken, String lexema, String msgError, int fila, int columna){
        //creamos un  token auxiliar
        TokenError tokenErrorAux = new TokenError(tipoToken, lexema, msgError, fila, columna);
        //Agregamos al listado
        listadoErroresLexicos.add(tokenErrorAux);
    }

    //Obtenemos el arrLust de los errores lexicos
    public ArrayList<TokenError> obtenerListadoErroresLexicos(){
        return listadoErroresLexicos;
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public LexerLectura(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 180) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(ParserLecturaSym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { addErrorLexico ("LEXICO", yytext(), "Token no valido", yyline + 1, yycolumn + 1);
            } 
            // fall through
          case 18: break;
          case 2: 
            { /*                                                                                     */
            } 
            // fall through
          case 19: break;
          case 3: 
            { return retornarSimbolo(NUMERO   , "NUMERO"          , yytext(), yyline + 1, yycolumn + 1);
            } 
            // fall through
          case 20: break;
          case 4: 
            { return retornarSimbolo(PAREN_INI       , "PAREN_INI"       , yytext(), yyline + 1, yycolumn + 1);
            } 
            // fall through
          case 21: break;
          case 5: 
            { return retornarSimbolo(PUNTO_COMA      , "PUNTO_COMA"      , yytext(), yyline + 1, yycolumn + 1);
            } 
            // fall through
          case 22: break;
          case 6: 
            { return retornarSimbolo(PAREN_FIN       , "PAREN_FIN"       , yytext(), yyline + 1, yycolumn + 1);
            } 
            // fall through
          case 23: break;
          case 7: 
            { return retornarSimbolo(COMA            , "COMA"            , yytext(), yyline + 1, yycolumn + 1);
            } 
            // fall through
          case 24: break;
          case 8: 
            { return retornarSimbolo(ALFANUM          , "ALFANUM"         , yytext().replaceAll("â€œ","\"").replaceAll("â€?","\""), yyline + 1, yycolumn + 1);
            } 
            // fall through
          case 25: break;
          case 9: 
            { return retornarSimbolo(SALON            , "SALON"           , yytext(), yyline + 1, yycolumn + 1);
            } 
            // fall through
          case 26: break;
          case 10: 
            { return retornarSimbolo(CURSO            , "CURSO"           , yytext(), yyline + 1, yycolumn + 1);
            } 
            // fall through
          case 27: break;
          case 11: 
            { return retornarSimbolo(USUARIO          , "USUARIO"         , yytext(), yyline + 1, yycolumn + 1);
            } 
            // fall through
          case 28: break;
          case 12: 
            { return retornarSimbolo(ASIGNAR          , "ASIGNAR"         , yytext(), yyline + 1, yycolumn + 1);
            } 
            // fall through
          case 29: break;
          case 13: 
            { return retornarSimbolo(HORARIO          , "HORARIO"         , yytext(), yyline + 1, yycolumn + 1);
            } 
            // fall through
          case 30: break;
          case 14: 
            { return retornarSimbolo(EDIFICIO         , "EDIFICIO"        , yytext(), yyline + 1, yycolumn + 1);
            } 
            // fall through
          case 31: break;
          case 15: 
            { return retornarSimbolo(ESTUDIANTE       , "ESTUDIANTE"      , yytext(), yyline + 1, yycolumn + 1);
            } 
            // fall through
          case 32: break;
          case 16: 
            { return retornarSimbolo(CATEDRATICO      , "CATEDRATICO"     , yytext(), yyline + 1, yycolumn + 1);
            } 
            // fall through
          case 33: break;
          case 17: 
            { return retornarSimbolo(COLABORADOR      , "COLABORADOR"     , yytext(), yyline + 1, yycolumn + 1);
            } 
            // fall through
          case 34: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }

  /**
   * Converts an int token code into the name of the
   * token by reflection on the cup symbol class/interface sym
   *
   * This code was contributed by Karl Meissner <meissnersd@yahoo.com>
   */
  private String getTokenName(int token) {
    try {
      java.lang.reflect.Field [] classFields = ParserLecturaSym.class.getFields();
      for (int i = 0; i < classFields.length; i++) {
        if (classFields[i].getInt(null) == token) {
          return classFields[i].getName();
        }
      }
    } catch (Exception e) {
      e.printStackTrace(System.err);
    }

    return "UNKNOWN TOKEN";
  }

  /**
   * Same as next_token but also prints the token to standard out
   * for debugging.
   *
   * This code was contributed by Karl Meissner <meissnersd@yahoo.com>
   */
  public java_cup.runtime.Symbol debug_next_token() throws java.io.IOException {
    java_cup.runtime.Symbol s = next_token();
    System.out.println( "line:" + (yyline+1) + " col:" + (yycolumn+1) + " --"+ yytext() + "--" + getTokenName(s.sym) + "--");
    return s;
  }

  /**
   * Runs the scanner on input files.
   *
   * This main method is the debugging routine for the scanner.
   * It prints debugging information about each returned token to
   * System.out until the end of file is reached, or an error occured.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String argv[]) {
    if (argv.length == 0) {
      System.out.println("Usage : java LexerLectura [ --encoding <name> ] <inputfile(s)>");
    }
    else {
      int firstFilePos = 0;
      String encodingName = "UTF-8";
      if (argv[0].equals("--encoding")) {
        firstFilePos = 2;
        encodingName = argv[1];
        try {
          java.nio.charset.Charset.forName(encodingName); // Side-effect: is encodingName valid? 
        } catch (Exception e) {
          System.out.println("Invalid encoding '" + encodingName + "'");
          return;
        }
      }
      for (int i = firstFilePos; i < argv.length; i++) {
        LexerLectura scanner = null;
        try {
          java.io.FileInputStream stream = new java.io.FileInputStream(argv[i]);
          java.io.Reader reader = new java.io.InputStreamReader(stream, encodingName);
          scanner = new LexerLectura(reader);
          while ( !scanner.zzAtEOF ) scanner.debug_next_token();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
