
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package gramatica;

/** CUP generated class containing symbol constants. */
public class ParserLecturaSym {
  /* terminals */
  public static final int HORARIO = 12;
  public static final int COMA = 5;
  public static final int USUARIO = 6;
  public static final int PUNTO_COMA = 4;
  public static final int ALFANUM = 15;
  public static final int SALON = 8;
  public static final int EOF = 0;
  public static final int PAREN_FIN = 3;
  public static final int CURSO = 9;
  public static final int NUMERO = 16;
  public static final int EDIFICIO = 7;
  public static final int PAREN_INI = 2;
  public static final int ESTUDIANTE = 10;
  public static final int COLABORADOR = 14;
  public static final int CATEDRATICO = 11;
  public static final int error = 1;
  public static final int ASIGNAR = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PAREN_INI",
  "PAREN_FIN",
  "PUNTO_COMA",
  "COMA",
  "USUARIO",
  "EDIFICIO",
  "SALON",
  "CURSO",
  "ESTUDIANTE",
  "CATEDRATICO",
  "HORARIO",
  "ASIGNAR",
  "COLABORADOR",
  "ALFANUM",
  "NUMERO"
  };
}

